[project]
name = "miter"
version = "0.1.0"
description = "Perfomance functions for iterables and sequences"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.scikit-build]
minimum-version = "build-system.requires"
build-dir = "build/{wheel_tag}"

[build-system]
requires = ["scikit-build-core>=0.10", "pybind11"]
build-backend = "scikit_build_core.build"
